[theme]
base = "light"

primaryColor = "#2563EB"            # Azul principal
backgroundColor = "#F6F8FC"         # Fundo do app
secondaryBackgroundColor = "#FFFFFF" # Cards e inputs
textColor = "#0F172A"

font = "sans serif"

# inputs
borderColor = "rgba(15, 23, 42, 0.18)"
inputBorderRadius = 8

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false

